// Hand-rolled, narrowly-typed surface for the schema we need at the app layer.
// Replaced by `pnpm --filter @uhs/db gen:types` once the schema settles —
// that command writes types.generated.ts. Until then, this is the contract.

export type Role = 'owner' | 'manager' | 'sales' | 'service' | 'readonly';

export interface Org {
  id: string;
  slug: string;
  name: string;
  brand_color: string | null;
  logo_url: string | null;
  default_markup_pct: number;
  sms_consent_text: string;
  status: 'active' | 'suspended' | 'archived';
  created_at: string;
  updated_at: string;
}

export interface OrgMember {
  user_id: string;
  org_id: string;
  role: Role;
  scoped_lots: string[] | null;
  status: 'active' | 'suspended' | 'pending';
  invited_by: string | null;
  invited_at: string | null;
  last_active_at: string | null;
  created_at: string;
}

export interface Lot {
  id: string;
  org_id: string;
  name: string;
  address: string | null;
  manager_id: string | null;
  deleted_at: string | null;
  deleted_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface PlatformAdmin {
  user_id: string;
  granted_by: string | null;
  granted_at: string;
  notes: string | null;
}

export interface OrgMembershipWithOrg extends OrgMember {
  orgs: Pick<Org, 'id' | 'slug' | 'name' | 'brand_color' | 'logo_url'>;
}

// ─── Inventory ────────────────────────────────────────────────────────────
export type HomeStatus = 'draft' | 'published' | 'hold' | 'sold' | 'archived';
export type HomeType = 'single' | 'double' | 'modular';

export interface Manufacturer {
  id: string;
  name: string;
  slug: string;
  logo_url: string | null;
  created_at: string;
}

export interface Home {
  id: string;
  org_id: string;
  lot_id: string | null;
  stock_no: string;
  name: string;
  manufacturer_id: string | null;
  model: string | null;
  type: HomeType;
  beds: number | null;
  baths: number | null;
  sqft: number | null;
  width_ft: number | null;
  length_ft: number | null;
  year_built: number | null;
  construction: string | null;
  base_price_cents: number;
  markup_pct: number;
  addons_cents: number;
  setup_cents: number;
  include_setup_in_price: boolean;
  starting_from: boolean;
  /** Generated by Postgres — never set client-side. */
  listed_price_cents: number;
  headline: string | null;
  description: string | null;
  status: HomeStatus;
  on_lot_since: string | null;
  is_featured: boolean;
  hide_from_search: boolean;
  created_by: string | null;
  updated_by: string | null;
  deleted_at: string | null;
  deleted_by: string | null;
  created_at: string;
  updated_at: string;
}

/** What anon (public site) sees — base_price_cents and markup_pct stripped. */
export interface PublicHome {
  id: string;
  org_id: string;
  lot_id: string | null;
  stock_no: string;
  name: string;
  manufacturer_id: string | null;
  model: string | null;
  type: HomeType;
  beds: number | null;
  baths: number | null;
  sqft: number | null;
  width_ft: number | null;
  length_ft: number | null;
  year_built: number | null;
  construction: string | null;
  listed_price_cents: number;
  starting_from: boolean;
  headline: string | null;
  description: string | null;
  on_lot_since: string | null;
  is_featured: boolean;
  created_at: string;
}

export interface HomePhoto {
  id: string;
  home_id: string;
  org_id: string;
  storage_path: string;
  sort_order: number;
  alt_text: string | null;
  width: number | null;
  height: number | null;
  created_at: string;
}

export interface PublicHomePhoto {
  id: string;
  home_id: string;
  storage_path: string;
  sort_order: number;
  alt_text: string | null;
  width: number | null;
  height: number | null;
}

export const HOME_PHOTO_BUCKET = 'home-photos';
export const QUOTE_PDF_BUCKET = 'quote-pdfs';
export const TRADEIN_PHOTO_BUCKET = 'tradein-photos';
export const ORG_BRANDING_BUCKET = 'org-branding';

/** Format cents → "$1,234". Used everywhere we render listed prices. */
export function formatCents(cents: number | null | undefined): string {
  if (cents == null) return '—';
  const dollars = Math.round(cents / 100);
  return '$' + dollars.toLocaleString();
}

// ─── Leads ────────────────────────────────────────────────────────────────
export type LeadSource =
  | 'quote_form' | 'contact_form' | 'phone' | 'walkin' | 'tradein' | 'import';
export type LeadStage = 'new' | 'in_progress' | 'quoted' | 'won' | 'lost';
export type MessageKind = 'inbound' | 'outbound' | 'note' | 'system';
export type MessageChannel = 'email' | 'sms' | 'call';

export interface Lead {
  id: string;
  org_id: string;
  home_id: string | null;
  contact_name: string;
  email: string | null;
  phone: string | null;
  source: LeadSource;
  stage: LeadStage;
  assignee_id: string | null;
  is_hot: boolean;
  next_action: string | null;
  reply_token: string;
  sms_consent: boolean;
  sms_consent_at: string | null;
  sms_consent_text: string | null;
  qualifier_payload: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
}

export interface LeadMessage {
  id: string;
  lead_id: string;
  org_id: string;
  kind: MessageKind;
  channel: MessageChannel | null;
  author_id: string | null;
  body: string;
  attachments: unknown;
  external_id: string | null;
  sent_at: string;
}

export interface Quote {
  id: string;
  org_id: string;
  lead_id: string;
  home_id: string;
  listed_price_cents: number;
  addons_jsonb: unknown;
  financing_jsonb: unknown;
  pdf_storage_path: string | null;
  public_token: string;
  expires_at: string;
  created_by: string | null;
  created_at: string;
}

export interface TradeIn {
  id: string;
  org_id: string;
  lead_id: string | null;
  contact_name: string;
  email: string | null;
  phone: string | null;
  year: number | null;
  make: string | null;
  model: string | null;
  size_w: number | null;
  size_l: number | null;
  condition_notes: string | null;
  photos_paths: string[] | null;
  offer_cents: number | null;
  status: 'submitted' | 'reviewed' | 'offered' | 'accepted' | 'declined';
  sms_consent: boolean;
  sms_consent_at: string | null;
  sms_consent_text: string | null;
  reviewed_by: string | null;
  reviewed_at: string | null;
  created_at: string;
  updated_at: string;
}
